### ISSUE TITLE
Still doesn't fix the problem

### ISSUE THREAD

**Issue by rikard-acst** [rikard-acst/gorunner#1]
Either we don't get color output by removing the line `cmd.Stderr = os.Stderr`
or, the same issue applies where the executable name is replaced as the tmux pane name

![image](https://user-images.githubusercontent.com/57632820/178494403-eae5c484-73c3-44b8-bd28-03c1dbd76b12.png)

**Comment by roopjm** [comment]
don't redirect stderror.
